# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: "esp8285"
  friendly_name: ESP8285

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0
  level: INFO
  logs:
    component: ERROR

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:
  - platform: esphome

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Activate web interface
web_server:
  port: 80

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------

substitutions:
  # Power meter source -----------------------------------------------------------
  # Define ip address of Fronius inverter
  power_meter_ip_address: "192.168.1.21"

  # LEDs -------------------------------------------------------------------------
  # Yellow LED is reflecting power meter
  yellow_led_pin: GPIO1

globals:
  - id: power_meter_activated
    type: int
    initial_value: "1"

# Uncomment the following lines if you want to use the source from github
# packages:
#   power_meter:
#     url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
#     file: solar_router/power_meter_fronius.yaml

# Remove the following lines if you want to use the source from github
packages:
  power_meter:
    <<: !include solar_router/power_meter_fronius.yaml

http_request:
  esp8266_disable_ssl_support: True
