# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: "esp8285"
  friendly_name: ESP8285

esp8266:
  board: esp8285

# Enable logging
logger:
  baud_rate: 115200
  level: INFO
  logs:
    component: ERROR
    http_request.arduino: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret proxy_api_encryption_key

# Enable over-the-air updates
ota:
  - platform: esphome

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # If you have a WiFi activity plannification, you may have to update the reboot timeout (Default: 15min)
  reboot_timeout: 24h
  
# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------

substitutions:
  # Power meter source -----------------------------------------------------------
  # Define ip address of Shelly EM probe
  power_meter_ip_address: "192.168.1.26:8000"
  emeter_index: "0"

  # LEDs -------------------------------------------------------------------------
  # Yellow LED is reflecting power meter
  yellow_led_pin: GPIO1

# power_meter_activated has to be set to 1 to activate the power measurment read
globals:
  - id: power_meter_activated
    type: int
    initial_value: "1"

# Uncomment the following lines if you want to use the source from github
# packages:
#   power_meter:
#     url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
#     file: solar_router/power_meter_shelly_em.yaml
#     refresh: 5s

# Remove the following lines if you want to use the source from github
packages:
  common:
    <<: !include solar_router/common.yaml
  power_meter:
    <<: !include solar_router/power_meter_shelly_em.yaml

http_request:
  esp8266_disable_ssl_support: True
