site_name: Solar Router for ESPHome
repo_url: https://github.com/XavierBerger/Solar-Router-for-ESPHome
repo_name: Fork me on GitHub
edit_uri: ""

nav:
  - Home: index.md
  - Disclamer: disclamer.md
  - Solar Router / Diverter: solar_router.md
  - Hardware: hardware.md
  - Firmware:
      - Overview: firmware.md
      - Installation: installation.md
      - Examples:
          - Standalone: standalone_example.md
          - With proxy: proxy_example.md
  - Power Meter:
      - Overview: power_meter.md
      - Fronius: power_meter_fronius.md
      - Home Assistant: power_meter_home_assistant.md
      - Proxy client: power_meter_proxy_client.md
      - Shelly EM: power_meter_shelly_em.md
  - Regulator:
      - Triac: regulator_triac.md
      - Solid State Relay: regulator_solid_state_relay.md
      - Mecanical relay: regulator_mecanical_relay.md
  - Engine: 
      - Variable regulation: engine.md
      - ON/OFF regulation: engine_on_off.md
  - Energy Counter: 
      - Theorical: energy_counter_theorical.md
  - Temperature limiter:
      - Overview: temperature_limiter.md
      - Home Assistant: temperature_limiter_home_assistant.md
      - DS18B20: temperature_limiter_DS18B20.md
  - HA configuration: ha_configuration.md
  - Contributing: contributing.md
  - ChangeLog: changelog.md
  - License: license.md
  - About: about.md

theme:
  features:
    - tabs
    - content.code.copy
  name: material

  font:
    text: Ubuntu
    code: Ubuntu Mono

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
  - glightbox
  - include-markdown
