# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: wt32-eth01-2
  friendly_name: wt32-eth01_2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 115200
  level: DEBUG
  logs:
    component: ERROR
    http_request.arduino: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret wt32_eth01_2_api_encryption_key

# Enable over-the-air updates
ota:
  - platform: esphome
    password: !secret wt32_eth01_2_ota_password

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configure ethernet
# Uncomment to activate ethernet with RJ45 and comment WiFi connection parameters
# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO0_IN
#   phy_addr: 1
#   power_pin: GPIO16

# Activate web interface
web_server:
  port: 80

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------

substitutions:
  # Power meter source -----------------------------------------------------------
  # Define ip address of Shelly EM probe
  power_meter_ip_address: "192.168.1.21"

  # LEDs -------------------------------------------------------------------------
  # Yellow LED is reflecting power meter
  yellow_led_pin: GPIO1

# power_meter_activated has to be set to 1 to activate the power measurment read
globals:
  - id: power_meter_activated
    type: int
    initial_value: "1"

# Uncomment the following lines if you want to use the source from github
# packages:
#   power_meter:
#     url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
#     file: solar_router/power_meter_fronius.yaml
#     refresh: 5s

# Remove the following lines if you want to use the source from github
packages:
  power_meter:
    <<: !include solar_router/power_meter_fronius.yaml
