# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: wt32-eth01-2
  friendly_name: wt32-eth01_2

esp32:
  board: wt32-eth01
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 115200
  level: INFO
  logs:
    component: ERROR
    light: ERROR
    http_request.arduino: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret wt32_eth01_2_api_encryption_key

# Enable over-the-air updates
ota:
  - platform: esphome
    password: !secret wt32_eth01_2_ota_password

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configure ethernet
# Uncomment to activate ethernet with RJ45 and comment WiFi connection parameters
# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO0_IN
#   phy_addr: 1
#   power_pin: GPIO16

# Activate web interface
web_server:
  port: 80

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------

substitutions:
  # Power meter source -----------------------------------------------------------
  # Define ip address of Power Meter (Fronius Inverter)
  power_meter_ip_address: "192.168.1.21"

  # LEDs -------------------------------------------------------------------------
  # Green LED is reflecting regulation status
  # Yellow LED is reflecting power meter
  green_led_pin: GPIO0
  yellow_led_pin: GPIO1

  # Regulator configuration ------------------------------------------------------
  # Define GPIO pin connected to mecanical relay.
  regulator_gate_pin: GPIO21

# Uncomment the following lines if you want to use the source from github
# packages:
#   power_meter:
#     url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
#     file: solar_router/power_meter_fronius.yaml
#     refresh: 5s

# Remove the following lines if you want to use the source from github
packages:
  common:
    <<: !include solar_router/common.yaml
  power_meter:
    <<: !include solar_router/power_meter_fronius.yaml
  regulator:
    <<: !include solar_router/regulator_mecanical_relay.yaml
  solar_router:
    <<: !include solar_router/engine_on_off.yaml
