# ----------------------------------------------------------------------------------------------------
# Define sensor for temperaturewer collection
# ----------------------------------------------------------------------------------------------------
substitutions:
  red_led_inverted: "False"

<<: !include temperature_limiter_common.yaml

sensor:
  # Sensor showing the temprature to monitor
  - platform: homeassistant
    id: safety_temperature
    entity_id: ${temperature_sensor}
    internal: False
    name: safety_temperature
    device_class: "temperature"
    unit_of_measurement: "°C"
    on_value:
      - script.execute:
          id: safety_limit_check
